[package]
name = "teloxide_tests_macros"
version = "0.2.0"
edition = "2021"

description = "Proc macros for teloxide_tests"
license = "MIT"

[dependencies]
syn = "2.0"
quote = "1.0"
proc-macro2 = "1.0"

[lib]
proc-macro = true
